//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aaCHAT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageSession
    {
        public int ID { get; set; }
        public string Body { get; set; }
        public string From { get; set; }
        public System.DateTime SentAt { get; set; }
        public int ChatSessionID { get; set; }
    
        public virtual ChatSession ChatSession { get; set; }
    }
}
